# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
